use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use cleaner_core::{config, engine};

/// Result returned to the frontend after a run.
#[derive(Serialize, Deserialize)]
pub struct CleanResult {
    pub messages: Vec<String>,
    pub moved: usize,
    pub errors: usize,
}

/// Return true if `cleaner.toml` exists inside the given folder.
#[tauri::command]
pub fn check_config(folder_path: String) -> bool {
    PathBuf::from(&folder_path).join("cleaner.toml").exists()
}

/// Write a sensible default `cleaner.toml` into `folder_path`.
#[tauri::command]
pub fn generate_default_config(folder_path: String) -> Result<(), String> {
    let dest = PathBuf::from(&folder_path).join("cleaner.toml");
    fs::write(&dest, DEFAULT_CONFIG_TEMPLATE)
        .map_err(|e| format!("Failed to write cleaner.toml: {e}"))
}

/// Run (or dry-run) the cleaner engine and return log messages + summary.
#[tauri::command]
pub fn run_cleaner(folder_path: String, dry_run: bool) -> Result<CleanResult, String> {
    let target = PathBuf::from(&folder_path);
    let config_path = target.join("cleaner.toml");

    let cfg = config::load_config(&config_path).map_err(|e| e.to_string())?;

    let summary = engine::run(&target, &cfg, "cleaner.toml", dry_run)
        .map_err(|e| e.to_string())?;

    Ok(CleanResult {
        messages: summary.messages,
        moved: summary.moved,
        errors: summary.errors,
    })
}

const DEFAULT_CONFIG_TEMPLATE: &str = r#"# cleaner.toml — generated by Folder Cleaner GUI
# Rules are evaluated top-to-bottom; the first matching rule wins.

[settings]
recursive = false
# unmatched_destination = "Other"

[[rules]]
name = "Images"
destination = "Images"
extensions = ["jpg", "jpeg", "png", "gif", "webp", "svg", "bmp", "tiff", "heic", "avif"]

[[rules]]
name = "Videos"
destination = "Videos"
extensions = ["mp4", "mov", "avi", "mkv", "wmv", "flv", "webm", "m4v", "mpg", "mpeg"]

[[rules]]
name = "Audio"
destination = "Audio"
extensions = ["mp3", "wav", "flac", "aac", "ogg", "wma", "m4a", "opus", "aiff"]

[[rules]]
name = "Documents"
destination = "Documents"
extensions = ["pdf", "doc", "docx", "txt", "rtf", "odt", "pages", "md"]

[[rules]]
name = "Spreadsheets"
destination = "Spreadsheets"
extensions = ["xls", "xlsx", "csv", "ods", "numbers"]

[[rules]]
name = "Presentations"
destination = "Presentations"
extensions = ["ppt", "pptx", "odp", "key"]

[[rules]]
name = "Archives"
destination = "Archives"
extensions = ["zip", "tar", "gz", "rar", "7z", "bz2", "xz", "dmg", "iso"]

[[rules]]
name = "Code"
destination = "Code"
extensions = ["rs", "py", "js", "ts", "go", "java", "c", "cpp", "h", "hpp", "sh", "rb", "php", "swift", "kt"]
"#;
